name: PR Lint
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-base:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --prefer-offline
          prisma generate

      - name: Lint
        run: pnpm lint
